services:
  miniodb:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: prj_python
      MINIO_ROOT_PASSWORD: 12345678
    volumes:
      - ~/minio/data:/data
    command: server --console-address ":9001" /data
    networks:
      - my-networks
    
  mongodb1:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ~/mongodb/data:/data/db
    networks:
      - my-networks
  
  qdrant:
    image: qdrant/qdrant:latest
    # restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage

configs:
  qdrant_config:
    content: |
      log_level: INFO   

      
networks:
  my-networks:
  
  
    
  